### ISSUE TITLE
English patch

### ISSUE THREAD

**Issue by ZanokRupert** [parshukov/Yak-40-Felis-for-X-Plane-11#2]
Hey,

First of all great work on keeping this plane alive in XP11 :+1: 
I was wondering if the English patch was missing or maybe I just can't find it. If its missing could you please add this? Because I don't understand Russian sadly.

Thanks!

**Comment by parshukov** [comment]
Hi! Try this one. If it is OK, I will upload a new release of this plane with this patch)
[Yak-40_ENG_patch.zip](https://github.com/parshukov/Yak-40-Felis-for-X-Plane-11/files/2538315/Yak-40_ENG_patch.zip)

**Comment by kbrandwijk** [comment]
I was already afraid I had to learn Russian for this one, but the language patch is great!
