### ISSUE TITLE
GNS430 manipulators visible

### ISSUE THREAD

**Issue by kbrandwijk** [parshukov/Yak-40-Felis-for-X-Plane-11#3]
I only noticed this after installing the English patch, but the manipulators on the GNS are visible (the black squares):
<img width="749" alt="image" src="https://user-images.githubusercontent.com/852069/48336354-61fcb380-e660-11e8-84b4-5ef4cd0ca014.png">

**Comment by parshukov** [comment]
heh! I will do smth with it) thanks)

**Comment by parshukov** [comment]
> 
> 
> I only noticed this after installing the English patch, but the manipulators on the GNS are visible (the black squares):
> <img alt="image" width="749" src="https://user-images.githubusercontent.com/852069/48336354-61fcb380-e660-11e8-84b4-5ef4cd0ca014.png">

try this one - put it in yak-40/cockpit/-PANELS-
[panel.zip](https://github.com/parshukov/Yak-40-Felis-for-X-Plane-11/files/2571226/panel.zip)

**Comment by kbrandwijk** [comment]
Yes, that did the trick. I'll leave the issue open for updating it in the repo.

**Comment by parshukov** [comment]
Just updated!)
